// Generated by tools/models/package_download.py. Do not edit hashes by hand.
import Foundation

extension SearchModelCatalog {
    static let production = SearchModelCatalog(
        modelName: "siglip2-base-patch16-256-w8",
        baseURL: URL(string: "https://github.com/misswell/PhotoVault/releases/download/v1.1.5/")!,
        files: [
        File(path: "SearchModelManifest.json", asset: "search-model--SearchModelManifest.json", bytes: 2478, sha256: "b577318b9e7fd853f83b94d1fe57eb469fa913ce52d740aca316413a0c0ecfd6"),
        File(path: "tokenizer-v1.bin", asset: "search-model--tokenizer-v1.bin", bytes: 5262055, sha256: "3184047555d845b4f54163efe06551bd7acfd8fa4c20b2607eec389dd2926f66"),
        File(path: "SigLIP2Vision.mlpackage/Data/com.apple.CoreML/model.mlmodel", asset: "search-model--SigLIP2Vision.mlpackage--Data--com.apple.CoreML--model.mlmodel", bytes: 151572, sha256: "b55d9609c5d157b72fd1a8496c92c8704b2140f903e1f20faff81c2896bbabb5"),
        File(path: "SigLIP2Vision.mlpackage/Data/com.apple.CoreML/weights/weight.bin", asset: "search-model--SigLIP2Vision.mlpackage--Data--com.apple.CoreML--weights--weight.bin", bytes: 92865088, sha256: "cfeec777370fe89cd4875ce9ca600e6c8ef640d7a53f1eebff3fefeb4e5cd957"),
        File(path: "SigLIP2Vision.mlpackage/Manifest.json", asset: "search-model--SigLIP2Vision.mlpackage--Manifest.json", bytes: 617, sha256: "1694d5b6a6b2d8e3d72fd118469aff228dc8343d2edb0ebd32c8ee3b102a0df5"),
        File(path: "SigLIP2Text.mlpackage/Data/com.apple.CoreML/model.mlmodel", asset: "search-model--SigLIP2Text.mlpackage--Data--com.apple.CoreML--model.mlmodel", bytes: 142995, sha256: "ad572df83fd2aa10f7c0ea96ae9b3ac71512a661dafd12c4c5743b83e3656d10"),
        File(path: "SigLIP2Text.mlpackage/Data/com.apple.CoreML/weights/weight.bin", asset: "search-model--SigLIP2Text.mlpackage--Data--com.apple.CoreML--weights--weight.bin", bytes: 283171904, sha256: "3461007bd81ad05fe2fb84b0c25f7723f044fdfa8c9f6798045e029ca3c2f9df"),
        File(path: "SigLIP2Text.mlpackage/Manifest.json", asset: "search-model--SigLIP2Text.mlpackage--Manifest.json", bytes: 617, sha256: "170a8e3f93a65162ec92ffdffa6ae1fa44971990c3b1e6f4f3d1de6b2913418c")
        ]
    )
}
