#!/usr/bin/env python3
"""Stage immutable release assets and generate the app's pinned download catalog.

Run install_models.py first. The app downloads each mlpackage member directly,
verifies its size and SHA-256, then compiles it using Core ML on the device.
No model weights are included in the app target or committed to git.
"""
import argparse
import hashlib
import json
from pathlib import Path
import shutil

REPO = Path(__file__).resolve().parents[2]
MODEL_DIR = REPO / "PhotoVault/Models"
CATALOG = REPO / "PhotoVault/Search/SearchModelCatalog.swift"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tag", required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    manifest = json.loads((MODEL_DIR / "SearchModelManifest.json").read_text())
    if manifest.get("installedPrecision") != "w8":
        raise SystemExit("The optional download must use the validated W8 models")
    paths = [MODEL_DIR / "SearchModelManifest.json", MODEL_DIR / "tokenizer-v1.bin"]
    for name in ("SigLIP2Vision.mlpackage", "SigLIP2Text.mlpackage"):
        members = sorted(p for p in (MODEL_DIR / name).rglob("*") if p.is_file())
        if not members:
            raise SystemExit(f"Missing {name}; run install_models.py first")
        paths.extend(members)
    args.output.mkdir(parents=True, exist_ok=True)
    entries = []
    checksums = []
    for path in paths:
        relative = path.relative_to(MODEL_DIR).as_posix()
        asset = "search-model--" + relative.replace("/", "--")
        with path.open("rb") as handle:
            digest = hashlib.file_digest(handle, "sha256").hexdigest()
        shutil.copy2(path, args.output / asset)
        entries.append(f'        File(path: {json.dumps(relative)}, asset: {json.dumps(asset)}, '
                       f'bytes: {path.stat().st_size}, sha256: "{digest}")')
        checksums.append(f"{digest}  {asset}")
    code = '''// Generated by tools/models/package_download.py. Do not edit hashes by hand.
import Foundation

extension SearchModelCatalog {
    static let production = SearchModelCatalog(
        modelName: %s,
        baseURL: URL(string: %s)!,
        files: [
%s
        ]
    )
}
''' % (json.dumps(manifest["name"]),
       json.dumps(f"https://github.com/misswell/PhotoVault/releases/download/{args.tag}/"),
       ",\n".join(entries))
    CATALOG.write_text(code)
    (args.output / "MODEL-SHA256SUMS").write_text("\n".join(checksums) + "\n")
    print(f"Staged {len(paths)} files ({sum(p.stat().st_size for p in paths):,} bytes)")
    print(CATALOG)


if __name__ == "__main__":
    main()
